// Human labels for the block "data-type" values used as node names in worksheets' content_html.
export const BLOCK_TYPE_LABELS: Record<string, string> = {
  'anagram-node': 'Anagramm',
  'article-plural': 'Artikel-/Plural-Training',
  'choose-correct-words': 'Wortwahl',
  'color-furniture': 'Möbel Farben',
  'communication-cards': 'Kommunikationskarten',
  messenger: 'Messenger',
  email: 'E-Mail',
  crossword: 'Kreuzworträtsel',
  'date-matching': 'Datum Zuordnen',
  'declination-table': 'Deklinationstabelle',
  dialogue: 'Dialog',
  domino: 'Domino',
  'error-correction': 'Fehlerkorrektur',
  'family-kinship': 'Familie',
  'fill-in-the-blank': 'Lückentext',
  'frayer-model': 'Frayer-Modell',
  'german-verb-table': 'Verbtabelle',
  'glossary-terms': 'Glossar',
  'information-gap-activity': 'Informationslücke',
  'inline-choice': 'Auswahl im Text',
  'learning-cards': 'Lernkarten',
  'learning-objective': 'Lernziel',
  lesetraining: 'Lesetraining',
  'letter-cloud': 'Buchstabenwolke',
  'letter-node': 'Buchstaben',
  'matching-pairs': 'Zuordnung',
  mch: 'Multiple Choice',
  mcm: 'Multiple Choice (mehrfach)',
  mcq: 'Multiple Choice',
  'mini-form': 'Formular',
  'occupation-portrait': 'Berufsporträt',
  'opening-hours': 'Öffnungszeiten',
  ordering: 'Reihenfolge',
  'rewrite-sentences': 'Sätze umschreiben',
  'sorting-categories': 'Sortieren',
  'time-matching': 'Zeit Zuordnen',
  timetable: 'Stundenplan',
  'true-false': 'Richtig/Falsch',
  'two-way-prepositions': 'Präpositionen',
  weather: 'Wetter',
  'word-bank': 'Wortspeicher',
  'word-grid': 'Buchstabengitter',
  'worksheet-table': 'Tabelle',
};
