import type { ComponentType } from 'react';
import type { Editor } from '@tiptap/core';
import {
  CheckSquare,
  LayoutGrid01,
  Rows01,
  SwitchHorizontal01,
  Toggle01Left,
  TypeSquare,
  Heading01,
  MessageChatSquare,
  Edit05,
  File02,
  Code02,
  Grid01,
  Clipboard,
  Table,
  BookOpen01,
  List,
  GraduationHat01,
  Image01,
} from '@untitledui/icons';

export type CustomBlockDefinition = {
  type: string;
  label: string;
  description: string;
  category: string;
  keywords: string[];
  Icon: ComponentType<{ className?: string }>;
  insert: (editor: Editor) => boolean;
};

export const CUSTOM_BLOCK_REGISTRY: CustomBlockDefinition[] = [
  {
    type: 'jsonImport',
    label: 'JSON Import',
    description: 'Import worksheet blocks from JSON and insert them at this position.',
    category: 'Import',
    keywords: ['json', 'import', 'worksheet', 'blocks', 'insert'],
    Icon: Code02,
    insert: () => false,
  },
  {
    type: 'communicationCards',
    label: 'Communication Cards',
    description: 'Single-sided DIN A4 landscape communication cards in a 4-up row layout.',
    category: 'Layout',
    keywords: ['communication', 'cards', 'a4', 'landscape', 'single-sided', 'print'],
    Icon: Grid01,
    insert: (editor) => editor.chain().focus().insertCommunicationCards().run(),
  },
  {
    type: 'learningCards',
    label: 'Learning cards',
    description: 'Print-ready DIN A8 cards in exclusive 3 × 3 duplex sheets.',
    category: 'Layout',
    keywords: ['learning', 'cards', 'flashcards', 'a8', 'duplex', 'print'],
    Icon: Grid01,
    insert: (editor) => editor.chain().focus().insertLearningCards().run(),
  },
  {
    type: 'pageBreak',
    label: 'Page break',
    description: 'Continue the following content on a new page.',
    category: 'Layout',
    keywords: ['page', 'break', 'new page', 'layout', 'print'],
    Icon: File02,
    insert: (editor) => editor.chain().focus().insertPageBreak().run(),
  },
  {
    type: 'customHeading',
    label: 'Heading',
    description: 'A branded heading with optional document numbering.',
    category: 'Content',
    keywords: ['heading', 'title', 'section', 'h1', 'h2', 'numbered'],
    Icon: Heading01,
    insert: (editor) => editor.chain().focus().insertCustomHeading().run(),
  },
  {
    type: 'richText',
    label: 'Rich Text',
    description: 'Formatted text with paragraphs, headings, lists, and links.',
    category: 'Content',
    keywords: ['rich', 'text', 'paragraph', 'heading', 'list', 'link', 'formatted'],
    Icon: TypeSquare,
    insert: (editor) => editor.chain().focus().insertRichText().run(),
  },
  {
    type: 'instructionBlock',
    label: 'Instruction',
    description: 'A standalone numbered instruction using the document design system.',
    category: 'Content',
    keywords: ['instruction', 'task', 'prompt', 'numbered', 'direction'],
    Icon: Clipboard,
    insert: (editor) => (
      editor.chain().focus().insertInstructionBlock().run()
    ),
  },
  {
    type: 'mediaLayout',
    label: 'Media layout',
    description: 'Images, image-and-text splits, galleries, and configurable grids.',
    category: 'Content',
    keywords: ['image', 'media', 'photo', 'gallery', 'grid', 'caption', 'text'],
    Icon: Image01,
    insert: (editor) => editor.chain().focus().insertMediaLayout().run(),
  },
  {
    type: 'letterNode',
    label: 'Letter Node',
    description: 'Decode answer words using numbered alphabet cells and helper letters.',
    category: 'Assessment',
    keywords: ['letter', 'alphabet', 'code', 'decode', 'word', 'helper'],
    Icon: Grid01,
    insert: (editor) => editor.chain().focus().insertLetterNode().run(),
  },
  {
    type: 'crossword',
    label: 'Crossword',
    description: 'Generate an intersecting crossword from answer and clue pairs.',
    category: 'Assessment',
    keywords: ['crossword', 'clues', 'terms', 'puzzle', 'vocabulary', 'grid'],
    Icon: Grid01,
    insert: (editor) => editor.chain().focus().insertCrossword().run(),
  },
  {
    type: 'errorCorrection',
    label: 'Error Correction Text',
    description: 'A controlled text with errors for learners to identify and correct.',
    category: 'Assessment',
    keywords: ['error', 'correction', 'grammar', 'spelling', 'editing', 'text'],
    Icon: Edit05,
    insert: (editor) => editor.chain().focus().insertErrorCorrection().run(),
  },
  {
    type: 'mcq',
    label: 'Multiple-choice question',
    description: 'A question with individually editable answer options.',
    category: 'Assessment',
    keywords: ['mcq', 'question', 'quiz', 'answers', 'single', 'multiple'],
    Icon: CheckSquare,
    insert: (editor) => editor.chain().focus().insertMCQ().run(),
  },
  {
    type: 'mcm',
    label: 'Multiple-choice matrix',
    description: 'Rows with independently configurable answer options.',
    category: 'Assessment',
    keywords: ['mcm', 'matrix', 'rows', 'individual options'],
    Icon: LayoutGrid01,
    insert: (editor) => editor.chain().focus().insertMCM().run(),
  },
  {
    type: 'mch',
    label: 'Header matrix',
    description: 'Rows that share up to four answer options in a header.',
    category: 'Assessment',
    keywords: ['mch', 'matrix', 'header', 'shared options', 'scale'],
    Icon: Rows01,
    insert: (editor) => editor.chain().focus().insertMCH().run(),
  },
  {
    type: 'articlePlural',
    label: 'Artikel- und Pluraltraining',
    description: 'German nouns with fixed article choices and a plural writing line.',
    category: 'Assessment',
    keywords: ['artikel', 'plural', 'der', 'das', 'die', 'nomen'],
    Icon: Rows01,
    insert: (editor) => editor.chain().focus().insertArticlePlural().run(),
  },
  {
    type: 'matchingPairs',
    label: 'Matching pairs',
    description: 'Two independent lists whose items are matched as pairs.',
    category: 'Assessment',
    keywords: ['matching', 'pairs', 'connect', 'left', 'right', 'assignment'],
    Icon: SwitchHorizontal01,
    insert: (editor) => editor.chain().focus().insertMatchingPairs().run(),
  },
  {
    type: 'domino',
    label: 'Domino',
    description: 'A 6 × 4 domino trail from ZIEL to ZIEL built from matching pairs.',
    category: 'Assessment',
    keywords: ['domino', 'chain', 'matching', 'pairs', 'trail', 'ZIEL'],
    Icon: SwitchHorizontal01,
    insert: (editor) => editor.chain().focus().insertDomino().run(),
  },
  {
    type: 'timeMatching',
    label: 'Zeit zuordnen',
    description: 'Analoge, digitale und deutsche Uhrzeitangaben einander zuordnen.',
    category: 'Assessment',
    keywords: ['zeit', 'uhr', 'analog', 'digital', 'offiziell', 'inoffiziell', 'matching'],
    Icon: SwitchHorizontal01,
    insert: (editor) => editor.chain().focus().insertTimeMatching().run(),
  },
  {
    type: 'dateMatching',
    label: 'Datum zuordnen',
    description: 'Kalender, numerische und ausgeschriebene Datumsangaben zuordnen.',
    category: 'Assessment',
    keywords: ['datum', 'kalender', 'tag', 'monat', 'jahr', 'date', 'matching'],
    Icon: SwitchHorizontal01,
    insert: (editor) => editor.chain().focus().insertDateMatching().run(),
  },
  {
    type: 'twoWayPrepositions',
    label: 'Wechselpräpositionen',
    description: 'Räumliche Kompositionen mit Akkusativ und Dativ üben.',
    category: 'Assessment',
    keywords: ['wechselpräpositionen', 'akkusativ', 'dativ', 'wo', 'wohin', 'präpositionen'],
    Icon: SwitchHorizontal01,
    insert: (editor) => editor.chain().focus().insertTwoWayPrepositions().run(),
  },
  {
    type: 'weather',
    label: 'Wetter',
    description: 'Schweizer Städte, Temperaturen und Wettersymbole auswerten.',
    category: 'Assessment',
    keywords: ['wetter', 'temperatur', 'schweiz', 'stadt', 'weather', 'mcq', 'richtig falsch'],
    Icon: Grid01,
    insert: (editor) => editor.chain().focus().insertWeather().run(),
  },
  {
    type: 'colorFurniture',
    label: 'Farben',
    description: 'Farben anhand verschiedener Möbelstücke erkennen und benennen.',
    category: 'Assessment',
    keywords: ['farben', 'möbel', 'sofa', 'tisch', 'stuhl', 'mcq', 'richtig falsch'],
    Icon: Grid01,
    insert: (editor) => editor.chain().focus().insertColorFurniture().run(),
  },
  {
    type: 'familyKinship',
    label: 'Familie | Verwandtschaftsgrade',
    description: 'Logikrätsel zu Familienbeziehungen mit Auswahl-, offenen oder Richtig/Falsch-Antworten.',
    category: 'Assessment',
    keywords: ['familie', 'verwandtschaft', 'verwandtschaftsgrade', 'onkel', 'tante', 'logikrätsel', 'mcq', 'richtig falsch'],
    Icon: BookOpen01,
    insert: (editor) => editor.chain().focus().insertFamilyKinship().run(),
  },
  {
    type: 'germanVerbTable',
    label: 'Verbtabelle Deutsch',
    description: 'Deutsche Verbformen nach Person, Numerus und Register darstellen.',
    category: 'Content',
    keywords: ['verb', 'konjugation', 'deutsch', 'singular', 'plural', 'präteritum'],
    Icon: Table,
    insert: (editor) => editor.chain().focus().insertGermanVerbTable().run(),
  },
  {
    type: 'occupationPortrait',
    label: 'Berufsporträt',
    description: 'Quellenbasiertes Berufs- oder Selbstporträt auf passendem Sprachniveau.',
    category: 'Content',
    keywords: ['beruf', 'portrait', 'selbstporträt', 'berufsberatung', 'arbeit'],
    Icon: BookOpen01,
    insert: (editor) => editor.chain().focus().insertOccupationPortrait().run(),
  },
  {
    type: 'trueFalse',
    label: 'True or false',
    description: 'Statements evaluated against two editable answer labels.',
    category: 'Assessment',
    keywords: ['true', 'false', 'boolean', 'statements', 'yes', 'no'],
    Icon: Toggle01Left,
    insert: (editor) => editor.chain().focus().insertTrueFalse().run(),
  },
  {
    type: 'fillInTheBlank',
    label: 'Fill in the blank',
    description: 'Text containing one or more answer placeholders.',
    category: 'Assessment',
    keywords: ['fill', 'blank', 'cloze', 'text', 'word', 'gap'],
    Icon: TypeSquare,
    insert: (editor) => editor.chain().focus().insertFillInTheBlank().run(),
  },
  {
    type: 'glossaryTerms',
    label: 'Glossary terms',
    description: 'Terms with a definition and an example.',
    category: 'Content',
    keywords: ['glossary', 'terms', 'definition', 'example', 'vocabulary'],
    Icon: Rows01,
    insert: (editor) => editor.chain().focus().insertGlossaryTerms().run(),
  },
  {
    type: 'frayerModel',
    label: 'Frayer model',
    description: 'Explore a concept through its definition, characteristics, examples, and non-examples.',
    category: 'Content',
    keywords: ['frayer', 'concept', 'vocabulary', 'definition', 'examples', 'organizer'],
    Icon: BookOpen01,
    insert: (editor) => editor.chain().focus().insertFrayerModel().run(),
  },
  {
    type: 'learningObjective',
    label: 'Learning objective box',
    description: 'Present an objective, curriculum code, and success criteria.',
    category: 'Content',
    keywords: ['learning', 'objective', 'curriculum', 'code', 'success criteria', 'goal'],
    Icon: GraduationHat01,
    insert: (editor) => (
      editor.chain().focus().insertLearningObjective().run()
    ),
  },
  {
    type: 'dialogue',
    label: 'Dialogue',
    description: 'Speaker-based dialogue rows with optional answer blanks.',
    category: 'Assessment',
    keywords: ['dialogue', 'conversation', 'speaker', 'chat', 'blank', 'original'],
    Icon: MessageChatSquare,
    insert: (editor) => editor.chain().focus().insertDialogue().run(),
  },
  {
    type: 'rewriteSentences',
    label: 'Rewrite Sentences',
    description: 'Incorrect sentences with space to write corrected versions.',
    category: 'Assessment',
    keywords: ['rewrite', 'sentence', 'correct', 'writing', 'solution'],
    Icon: Edit05,
    insert: (editor) => editor.chain().focus().insertRewriteSentences().run(),
  },
  {
    type: 'sortingCategories',
    label: 'Sorting Categories',
    description: 'Sort word-bank items into up to four categories.',
    category: 'Assessment',
    keywords: ['sorting', 'categories', 'classify', 'word bank', 'groups'],
    Icon: LayoutGrid01,
    insert: (editor) => editor.chain().focus().insertSortingCategories().run(),
  },
  {
    type: 'ordering',
    label: 'Ordering / sequencing',
    description: 'Number shuffled steps, events, sentences, or process stages.',
    category: 'Assessment',
    keywords: ['ordering', 'sequence', 'steps', 'events', 'process', 'number'],
    Icon: List,
    insert: (editor) => editor.chain().focus().insertOrdering().run(),
  },
  {
    type: 'wordGrid',
    label: 'Word Grid',
    description: 'A configurable word-search grid with selectable directions.',
    category: 'Assessment',
    keywords: ['word', 'grid', 'search', 'puzzle', 'letters', 'vocabulary'],
    Icon: Grid01,
    insert: (editor) => editor.chain().focus().insertWordGrid().run(),
  },
  {
    type: 'chooseCorrectWords',
    label: 'Choose Correct Words',
    description: 'Choose the correctly written word from generated variants.',
    category: 'Assessment',
    keywords: ['word', 'spelling', 'correct', 'choose', 'variants'],
    Icon: CheckSquare,
    insert: (editor) => (
      editor.chain().focus().insertChooseCorrectWords().run()
    ),
  },
  {
    type: 'inlineChoice',
    label: 'Inline Choice',
    description: 'Sentences with inline groups of selectable words.',
    category: 'Assessment',
    keywords: ['inline', 'choice', 'sentence', 'select', 'word', 'options'],
    Icon: CheckSquare,
    insert: (editor) => editor.chain().focus().insertInlineChoice().run(),
  },
  {
    type: 'miniForm',
    label: 'Mini Form',
    description: 'Extract information from prompts into configurable fields.',
    category: 'Assessment',
    keywords: ['mini', 'form', 'fields', 'extract', 'reading', 'profile'],
    Icon: Clipboard,
    insert: (editor) => editor.chain().focus().insertMiniForm().run(),
  },
  {
    type: 'worksheetTable',
    label: 'Table',
    description: 'A structured table with configurable 12-grid column spans.',
    category: 'Content',
    keywords: ['table', 'columns', 'rows', 'grid', 'span', 'blank', 'bold'],
    Icon: Table,
    insert: (editor) => editor.chain().focus().insertWorksheetTable().run(),
  },
];
