// Legacy UI strings that still live inside large editor/admin components.
// New UI should use a typed key from i18n.ts instead.
export const uiGerman: Record<string, string> = {
  '+ Add answer': '+ Antwort hinzufügen',
  '+ Add answer row': '+ Antwortzeile hinzufügen',
  '+ Add category': '+ Kategorie hinzufügen',
  '+ Add dialogue row': '+ Dialogzeile hinzufügen',
  '+ Add glossary term': '+ Glossarbegriff hinzufügen',
  '+ Add header option': '+ Kopfoption hinzufügen',
  '+ Add option': '+ Option hinzufügen',
  '+ Add pair': '+ Paar hinzufügen',
  '+ Add sentence': '+ Satz hinzufügen',
  '+ Add statement': '+ Aussage hinzufügen',
  '1 column': '1 Spalte',
  '2 columns': '2 Spalten',
  '3 columns': '3 Spalten',
  '12-column grid': '12-Spalten-Raster',
  '. Add a width factor with': '. Ergänze einen Breitenfaktor mit',
  'Accent color': 'Akzentfarbe',
  Academic: 'Akademisch',
  'Semi-Academic': 'Halbakademisch',
  'Accent text': 'Akzenttext',
  Actions: 'Aktionen',
  Active: 'Aktiv',
  Admin: 'Admin',
  'Add column': 'Spalte hinzufügen',
  'Add element': 'Element hinzufügen',
  'Add field': 'Feld hinzufügen',
  'Add image': 'Bild hinzufügen',
  'Add row': 'Zeile hinzufügen',
  'Add sentence': 'Satz hinzufügen',
  'Add word': 'Wort hinzufügen',
  Administration: 'Administration',
  Align: 'Ausrichtung',
  'Align custom-block content with the task instruction text.':
    'Inhalt benutzerdefinierter Blöcke am Aufgabentext ausrichten.',
  'All changes saved': 'Alle Änderungen gespeichert',
  'Answer labels': 'Antwortbeschriftungen',
  'Answer rows': 'Antwortzeilen',
  Answers: 'Antworten',
  'Applies to all blanks without an explicit': 'Gilt für alle Lücken ohne expliziten',
  Blank: 'Lücke',
  'Blank divider row': 'Leere Trennzeile',
  Blockquote: 'Zitatblock',
  Bold: 'Fett',
  Brand: 'Marke',
  'Brand Profiles': 'Markenprofile',
  'Brand profiles': 'Markenprofile',
  'Browse media': 'Medien durchsuchen',
  'Bottom to top': 'Von unten nach oben',
  'Bullet list': 'Aufzählung',
  Center: 'Zentriert',
  Choice: 'Auswahl',
  'Choose Correct Words': 'Korrekte Wörter wählen',
  'Choose an image for this worksheet item.': 'Wähle ein Bild für dieses Arbeitsblatt-Element.',
  'Choose the correct answer for each row.': 'Wähle für jede Zeile die richtige Antwort.',
  'Choose the correct answer.': 'Wähle die richtige Antwort.',
  'Clear document': 'Dokument leeren',
  'Close block palette': 'Blockauswahl schließen',
  'Close media library': 'Medienbibliothek schließen',
  'Code block': 'Codeblock',
  'Color coding': 'Farbcodierung',
  Columns: 'Spalten',
  'Complete the dialogue.': 'Vervollständige den Dialog.',
  'Context': 'Kontext',
  'Content indentation': 'Einzug des Inhalts',
  'Copy as HTML': 'Als HTML kopieren',
  'Correct answers': 'Richtige Antworten',
  'Correct option': 'Richtige Option',
  'Correct value': 'Richtiger Wert',
  'Create brand profile': 'Markenprofil erstellen',
  Custom: 'Benutzerdefiniert',
  Dashboard: 'Übersicht',
  'Custom 1': 'Benutzerdefiniert 1',
  'Custom 2': 'Benutzerdefiniert 2',
  'Date format': 'Datumsformat',
  'Default blank width': 'Standardbreite für Lücken',
  'Default brand (Eduit)': 'Standardmarke (Eduit)',
  'Default font stack': 'Standard-Schriftfamilie',
  'Default profile': 'Standardprofil',
  'No parent profile': 'Kein übergeordnetes Profil',
  'Default ·': 'Standard ·',
  'Default text': 'Standardtext',
  Definition: 'Definition',
  Delete: 'Löschen',
  'Delete page break': 'Seitenumbruch löschen',
  Description: 'Beschreibung',
  'Detected answers': 'Erkannte Antworten',
  Dialogue: 'Dialog',
  Documents: 'Dokumente',
  'Document size': 'Dokumentformat',
  'Document style': 'Dokumentstil',
  'DIN A4 Landscape': 'DIN A4 Querformat',
  'DIN A4 Portrait': 'DIN A4 Hochformat',
  'Draft · autosaved locally': 'Entwurf · lokal automatisch gespeichert',
  'Edit brand profile': 'Markenprofil bearbeiten',
  'Parent profile': 'Übergeordnetes Profil',
  'Reset settings to parent': 'Einstellungen auf übergeordnetes Profil zurücksetzen',
  'All settings are inherited from the parent.':
    'Alle Einstellungen werden vom übergeordneten Profil übernommen.',
  Educational: 'Pädagogisch',
  'Educational is spacious. Semi-Academic keeps the academic layout with slightly larger body text. Academic is the most compact.':
    '„Educational“ ist großzügig. „Semi-Academic“ behält das akademische Layout mit etwas grösserem Fliesstext bei. „Academic“ ist am kompaktesten.',
  'Enter a prompt and one expected value for every field.':
    'Gib für jedes Feld eine Aufforderung und einen erwarteten Wert ein.',
  'Enter dialogue text': 'Dialogtext eingeben',
  'Enter the correct sentence': 'Den richtigen Satz eingeben',
  'Enter the sentence or question.': 'Satz oder Frage eingeben.',
  'Enter the sentence to rewrite': 'Den umzuschreibenden Satz eingeben',
  'Esc Close': 'Esc Schließen',
  Example: 'Beispiel',
  'Example color': 'Beispielfarbe',
  'Example color picker': 'Beispielfarbe auswählen',
  'Example font size (px)': 'Beispiel-Schriftgröße (px)',
  'Example font stack': 'Beispiel-Schriftfamilie',
  'Example styling': 'Beispielgestaltung',
  Exporting: 'Wird exportiert',
  'Export PDF': 'PDF exportieren',
  False: 'Falsch',
  'Fill in the blank': 'Lückentext',
  'Fill in the blanks with the correct words.': 'Fülle die Lücken mit den richtigen Wörtern.',
  'Filled badge': 'Gefülltes Abzeichen',
  'Fixed number width': 'Feste Nummernbreite',
  Form: 'Formular',
  'Form field labels': 'Formularfeld-Beschriftungen',
  'General width': 'Allgemeine Breite',
  Glossary: 'Glossar',
  'Glossary terms': 'Glossarbegriffe',
  Grid: 'Raster',
  'Header matrix': 'Kopfmatrix',
  'Header options': 'Kopfoptionen',
  Heading: 'Überschrift',
  'Heading 1': 'Überschrift 1',
  'Heading 2': 'Überschrift 2',
  'Heading numbering by level': 'Überschriftennummerierung nach Ebene',
  'Hide blank numbers': 'Lückennummern ausblenden',
  Image: 'Bild',
  Inactive: 'Inaktiv',
  'Include N/A column': 'Spalte „k. A.“ einblenden',
  'Inline Choice': 'Inline-Auswahl',
  Input: 'Eingabe',
  'Insert a blank with': 'Lücke einfügen mit',
  'Insert block': 'Block einfügen',
  'Insert custom block': 'Benutzerdefinierten Block einfügen',
  Instruction: 'Arbeitsanweisung',
  'Inverse / white': 'Invertiert / Weiß',
  Italic: 'Kursiv',
  Item: 'Element',
  'Keep from left': 'Von links beibehalten',
  'Keep from right': 'Von rechts beibehalten',
  Left: 'Links',
  'Left to right': 'Von links nach rechts',
  Lessons: 'Lektionen',
  'Left and matching right': 'Links und passende rechte Seite',
  'Left item': 'Linkes Element',
  'Letter directions': 'Buchstabenrichtungen',
  Level: 'Ebene',
  Library: 'Bibliothek',
  'Loading profiles…': 'Profile werden geladen…',
  'Logo URL': 'Logo-URL',
  'Logo scale': 'Logo-Skalierung',
  'Mark correct': 'Richtige markieren',
  'Mark each statement as true or false.': 'Markiere jede Aussage als richtig oder falsch.',
  'Match the items on the left with the items on the right.':
    'Ordne die Elemente links den passenden Elementen rechts zu.',
  'Matching pairs': 'Zuordnungspaare',
  'Matching right item': 'Passendes rechtes Element',
  'Max. 3 options each': 'Max. 3 Optionen pro Zeile',
  'Max. 4': 'Max. 4',
  'Media library': 'Medienbibliothek',
  Media: 'Medien',
  'Mini Form': 'Mini-Formular',
  'Multiple answers': 'Mehrere Antworten',
  'Multiple choice': 'Einfachauswahl',
  'Multiple-choice matrix': 'Multiple-Choice-Matrix',
  'Multiplies the design-system row height in 0.1 steps.':
    'Multipliziert die Zeilenhöhe des Designsystems in 0,1-Schritten.',
  'New profile': 'Neues Profil',
  'New word': 'Neues Wort',
  Name: 'Name',
  'N/A': 'k. A.',
  'No blocks found': 'Keine Blöcke gefunden',
  'No correct option': 'Keine richtige Option',
  'No correct value': 'Kein richtiger Wert',
  'No valid blank markers found.': 'Keine gültigen Lückenmarkierungen gefunden.',
  'NE to SW': 'NO nach SW',
  'NW to SE': 'NW nach SO',
  'Number and heading text are styled independently at every level.':
    'Nummer und Überschriftentext werden auf jeder Ebene unabhängig gestaltet.',
  'Number color': 'Nummernfarbe',
  'Number format': 'Nummernformat',
  'Number weight': 'Nummernschnitt',
  Numbered: 'Nummeriert',
  'Numbering and locale': 'Nummerierung und Region',
  'Option columns': 'Optionsspalten',
  'Page break': 'Seitenumbruch',
  'PDF export failed.': 'PDF-Export fehlgeschlagen.',
  Pair: 'Paar',
  Pairs: 'Paare',
  'Placeholder flow — storage will be connected later':
    'Platzhalterablauf – der Speicher wird später angebunden',
  'Placeholder image': 'Platzhalterbild',
  'Primary color': 'Primärfarbe',
  'Primary text': 'Primärtext',
  Profiles: 'Profile',
  Publish: 'Veröffentlichen',
  Question: 'Frage',
  Recent: 'Zuletzt verwendet',
  Redo: 'Wiederholen',
  'Regenerate grid': 'Raster neu erzeugen',
  Replace: 'Ersetzen',
  'Replace image': 'Bild ersetzen',
  'Review the following glossary terms.': 'Lies die folgenden Glossarbegriffe.',
  Rewrite: 'Umschreiben',
  'Rewrite Sentences': 'Sätze umschreiben',
  'Rewrite the sentences correctly.': 'Schreibe die Sätze richtig.',
  Right: 'Rechts',
  'Right to left': 'Von rechts nach links',
  'Right-align all counters in the width of one H1 glyph.':
    'Alle Zähler rechtsbündig auf die Breite eines H1-Zeichens ausrichten.',
  'Row height': 'Zeilenhöhe',
  Rows: 'Zeilen',
  'Save profile': 'Profil speichern',
  Saved: 'Gespeichert',
  'Saving…': 'Wird gespeichert…',
  'Scaling keeps the logo’s top-right origin and does not change header geometry.':
    'Die Skalierung behält den oberen rechten Ursprung des Logos bei und verändert die Kopfgeometrie nicht.',
  'Search blocks…': 'Blöcke suchen…',
  'Search custom blocks': 'Benutzerdefinierte Blöcke suchen',
  'SE to NW': 'SO nach NW',
  Settings: 'Einstellungen',
  Sentences: 'Sätze',
  'Show first as example': 'Erstes als Beispiel anzeigen',
  'Show header row': 'Kopfzeile anzeigen',
  'Show original': 'Original anzeigen',
  'Show solutions': 'Lösungen anzeigen',
  'Show word bank': 'Wortliste anzeigen',
  'Show word list': 'Wortliste anzeigen',
  'Shuffle choices': 'Auswahl mischen',
  'Shuffle items': 'Elemente mischen',
  'Shuffle right': 'Rechte Seite mischen',
  'Shuffle word bank': 'Wortliste mischen',
  'Single answer': 'Eine Antwort',
  Slug: 'Slug',
  Solution: 'Lösung',
  'Solution color': 'Lösungsfarbe',
  'Solution color picker': 'Lösungsfarbe auswählen',
  'Solution font size (px)': 'Lösungs-Schriftgröße (px)',
  'Solution font stack': 'Lösungs-Schriftfamilie',
  'Solution styling': 'Lösungsgestaltung',
  'Sort the items into the correct categories.': 'Sortiere die Elemente in die richtigen Kategorien.',
  'Start writing…': 'Beginne zu schreiben…',
  Sorting: 'Sortieren',
  'Sorting Categories': 'Kategorien sortieren',
  Span: 'Breite',
  Speaker: 'Sprecher',
  Statements: 'Aussagen',
  Status: 'Status',
  Strikethrough: 'Durchgestrichen',
  'System profile · protected from deletion': 'Systemprofil · vor dem Löschen geschützt',
  System: 'System',
  'SW to NE': 'SW nach NO',
  Table: 'Tabelle',
  'Task Numbering': 'Aufgabennummerierung',
  'Task number color': 'Farbe der Aufgabennummer',
  'Task number style': 'Stil der Aufgabennummer',
  'Task number weight': 'Schnitt der Aufgabennummer',
  Term: 'Begriff',
  'Term column width': 'Breite der Begriffsspalte',
  Text: 'Text',
  'Text color': 'Textfarbe',
  'Text weight': 'Textschnitt',
  'Top to bottom': 'Von oben nach unten',
  True: 'Richtig',
  'True or false': 'Richtig oder falsch',
  'Try a name, category, or keyword.': 'Versuche es mit einem Namen, einer Kategorie oder einem Stichwort.',
  Undo: 'Rückgängig',
  Upload: 'Hochladen',
  'Upload an image': 'Bild hochladen',
  'Use Cmd+B or Ctrl+B for bold and': 'Verwende Cmd+B oder Ctrl+B für Fett und',
  'US Letter Landscape': 'US Letter Querformat',
  'US Letter Portrait': 'US Letter Hochformat',
  'Uses the active brand format.': 'Verwendet das aktive Markenformat.',
  'Visual identity': 'Visuelle Identität',
  'Word Grid': 'Wortraster',
  Words: 'Wörter',
  'Worksheet image': 'Arbeitsblattbild',
  'Worksheet illustration': 'Arbeitsblattillustration',
  'Could not delete brand profile.': 'Markenprofil konnte nicht gelöscht werden.',
  'Could not load brand profiles.': 'Markenprofile konnten nicht geladen werden.',
  'Could not load worksheet.': 'Arbeitsblatt konnte nicht geladen werden.',
  'Could not save brand profile.': 'Markenprofil konnte nicht gespeichert werden.',
  'Could not save solution setting.': 'Lösungseinstellung konnte nicht gespeichert werden.',
  '↑↓ Navigate': '↑↓ Navigieren',
  '↵ Insert': '↵ Einfügen',
  factor: 'Faktor',
  'for blanks.': 'für Lücken.',
};
